version: '3'

services:
  task5:
    build: ./
    container_name: t5
  proxy-nginx:
    image: nginx
    container_name: proxy
    ports:
      - 80:8080
    volumes:
      - ./nginx-2.conf:/etc/nginx/nginx.conf